# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitws < Formula
  desc "Separate work/personal Git identities. Keys, SSH aliases, and guards."
  homepage "https://gitws.dev"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitworkspaces/gitws/releases/download/v1.0.0/gitws_1.0.0_darwin_amd64.tar.gz"
      sha256 "1ccc7602bc0b391b4bcbeb169ad52bcc6f86ff1eea16139283324e8fa47e1d4f"

      def install
        bin.install "gitws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitworkspaces/gitws/releases/download/v1.0.0/gitws_1.0.0_darwin_arm64.tar.gz"
      sha256 "e4ba195415b8438ab804f61f3f9ac9c52cec2b2a6a72d37ce09a84446749b093"

      def install
        bin.install "gitws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitworkspaces/gitws/releases/download/v1.0.0/gitws_1.0.0_linux_amd64.tar.gz"
      sha256 "ca6ac57743109f1dd85f1ff73206ea02675c076101b4697d4b5cf7067650b35d"
      def install
        bin.install "gitws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitworkspaces/gitws/releases/download/v1.0.0/gitws_1.0.0_linux_arm64.tar.gz"
      sha256 "0067938d1a6317dc10263504ee46ff7a8d44ed980b56b2a2485efa9283e17ea2"
      def install
        bin.install "gitws"
      end
    end
  end

  test do
    system "#{bin}/gitws", "--help"
  end
end
